name: Deploy
on: workflow_dispatch
env:
  NODE-VERSION: 20
  NPM-VERSION: 10.8.2
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: node setup
        uses: ./.github/actions/setup-node
        with:
          NODE-VERSION: ${{ env.NODE-VERSION }}
          NPM-VERSION: ${{ env.NPM-VERSION }}
      - name: app build
        uses: ./.github/actions/build
        with:
          app-name: 'react-newrelic-demo'
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          preCommands: |
            echo "*** pre commands ***"
            echo `pwd`
            npx wrangler --version
            npm install wrangler@latest
            echo "******"



