name: Deploy
on: workflow_dispatch
permissions:
  deployments: write
  contents: read
env:
  NODE-VERSION: 20
  NPM-VERSION: 10.8.2
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: node setup
        uses: ./.github/actions/setup-node
        with:
          NODE-VERSION: ${{ env.NODE-VERSION }}
          NPM-VERSION: ${{ env.NPM-VERSION }}
      - name: app build
        uses: ./.github/actions/build
        with:
          app-name: 'react-newrelic-demo'
      - name: Upload source maps to New Relic
        uses: ./.github/actions/upload-sourcemaps
        with:
          app-name: 'react-newrelic-demo'
          new-relic-api-key: ${{ secrets.NEW_RELIC_USER_KEY }}
          new-relic-app-id: ${{ secrets.NEW_RELIC_APP_ID }}
          base-url: 'https://react-router-newrelic-demo.pages.dev'
      - name: デプロイ対象ファイル一覧の確認
        shell: bash
        run: |
          echo "Cloudflare Pages へのデプロイ対象ファイル一覧:"
          find apps/react-newrelic-demo/dist -type f | sort
          echo "ソースマップファイルの確認:"
          find apps/react-newrelic-demo/dist -name "*.js.map" -type f | wc -l
          echo "JSファイルの確認:"
          find apps/react-newrelic-demo/dist -name "*.js" -type f | wc -l
      - name: Publich
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'react-router-newrelic-demo'
          directory: 'apps/react-newrelic-demo/dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
